name: gestor_de_datos
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Tus dependencias actuales
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8

  # ¡¡VERSIONES NUEVAS DE FIREBASE!! 🔥
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true