// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF0_TV9msN67VV0WVUsreSxKndrmXz4Yg',
    appId: '1:337796922523:web:26d7ca673e1d743d4c1a3e',
    messagingSenderId: '337796922523',
    projectId: 'gestor-de-datos-b590a',
    authDomain: 'gestor-de-datos-b590a.firebaseapp.com',
    storageBucket: 'gestor-de-datos-b590a.firebasestorage.app',
    measurementId: 'G-8H3PY4NPZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM-Z7S0ntk5FcL-kvsnXy40-MmsA-3KK4',
    appId: '1:337796922523:android:b7b2db66204007124c1a3e',
    messagingSenderId: '337796922523',
    projectId: 'gestor-de-datos-b590a',
    storageBucket: 'gestor-de-datos-b590a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQu4a_gYEs0l5esALtKWjCgQzFCO7KP2M',
    appId: '1:337796922523:ios:537891cd30879d924c1a3e',
    messagingSenderId: '337796922523',
    projectId: 'gestor-de-datos-b590a',
    storageBucket: 'gestor-de-datos-b590a.firebasestorage.app',
    iosBundleId: 'com.example.gestorDeDatos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQu4a_gYEs0l5esALtKWjCgQzFCO7KP2M',
    appId: '1:337796922523:ios:537891cd30879d924c1a3e',
    messagingSenderId: '337796922523',
    projectId: 'gestor-de-datos-b590a',
    storageBucket: 'gestor-de-datos-b590a.firebasestorage.app',
    iosBundleId: 'com.example.gestorDeDatos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF0_TV9msN67VV0WVUsreSxKndrmXz4Yg',
    appId: '1:337796922523:web:defba7655477013a4c1a3e',
    messagingSenderId: '337796922523',
    projectId: 'gestor-de-datos-b590a',
    authDomain: 'gestor-de-datos-b590a.firebaseapp.com',
    storageBucket: 'gestor-de-datos-b590a.firebasestorage.app',
    measurementId: 'G-W0JY6MJJ5T',
  );
}
